name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: sudo apt install docker-compose

      - name: pull docker images
        run: cd test && docker-compose up -d

      - name: use default config
        run: docker cp test/qq.yaml yunzai-bot:/app/Yunzai-Bot/config/config

      - name: install plugin dependencies
        run: docker exec yunzai-bot sh -c "cd plugins/l-plugin/ && pnpm install"

      - name: copy test script
        run: docker cp test/test.sh yunzai-bot:/app/Yunzai-Bot

      - name: run test script
        run: docker exec yunzai-bot sh test.sh

      - name: check log
        run: sudo chown -R $(whoami) ./test/yunzai/logs && sudo chmod -R 777 ./test/yunzai/logs && sh -c "! grep -rq 'ERRO' ./test/yunzai/logs"
