name: yunzai test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: sudo apt install docker-compose

      - name: pull docker images
        run: cd test && docker-compose up -d

      - name: use default config
        run: docker cp test/qq.yaml yunzai-bot:/app/Yunzai-Bot/config/config

      - name: install plugin dependencies
        run: docker exec yunzai-bot sh -c "cd plugins/l-plugin/ && pnpm install"

      - name: replace test script config
        run: |
          node ./lib/tools/test.js 塔罗牌
          node ./lib/tools/test.js 每日一题
          node ./lib/tools/test.js "r 114514 1919810"
          node ./lib/tools/test.js "今天吃什么"
          node ./lib/tools/test.js "tex 9>10"
          node ./lib/tools/test.js 求签

      - name: run test script
        run: docker exec yunzai-bot npm run test
